### ISSUE TITLE
BentoVLLM Service Fails to Start on Linux Server Due to Pydantic Related Errors

### ISSUE THREAD

**Issue by Juhong-Namgung** [bentoml/BentoVLLM#14]
Hello,

I attempted to run a BentoVLLM example on a Linux server, ensuring all prerequisites were met and following the installation guide accordingly. 

However, when trying to run the BentoML Service, I encountered an error preventing the service from starting. 

The error log suggests an issue related to pydantic, and updating the version does not resolve the issue. The detailed error message is as follows:

> ubuntu@ip-172-31-55-53:./serving/BentoVLLM$ bentoml serve .
2024-03-12T10:06:30+0900 [INFO] [cli] Starting production HTTP BentoServer from "service:VLLM" listening on http://localhost:3000 (Press CTRL+C to quit)
INFO 03-12 10:06:35 llm_engine.py:87] Initializing an LLM engine with config: model='mistralai/Mistral-7B-Instruct-v0.2', tokenizer='mistralai/Mistral-7B-Instruct-v0.2', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 03-12 10:06:39 weight_utils.py:163] Using model weights format ['*.safetensors']
INFO 03-12 10:07:02 llm_engine.py:357] # GPU blocks: 2910, # CPU blocks: 2048
INFO 03-12 10:07:03 model_runner.py:684] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 03-12 10:07:03 model_runner.py:688] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 03-12 10:07:08 model_runner.py:756] Graph capturing finished in 5 secs.

> 2024-03-12T10:07:09+0900 [ERROR] [entry_service:VLLM_OpenAI:1] Initializing service error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/type_adapter.py", line 149, in __init__
    core_schema = _getattr_no_parents(type, '__pydantic_core_schema__')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/type_adapter.py", line 94, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

>During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 461, in _generate_schema
    obj = _typing_extra.evaluate_fwd_ref(obj, globalns=self.types_namespace)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/_internal/_typing_extra.py", line 414, in evaluate_fwd_ref
    return ref._evaluate(globalns=globalns, localns=localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'CompletionRequest' is not defined

>The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/_bentoml_sdk/service/factory.py", line 220, in __call__
    return self.inner()
  File "/home/ubuntu/serving/BentoVLLM/bentovllm_openai/utils.py", line 116, in __init__
    async def create_completion(request: "CompletionRequest", raw_request: Request):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastapi/routing.py", line 956, in decorator
    self.add_api_route(
  ...
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 463, in _generate_schema
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'CompletionRequest' is not defined

> For further information visit https://errors.pydantic.dev/2.0.2/u/undefined-annotation

...

> INFO 03-12 10:07:10 serving_chat.py:302] Using default chat template:
INFO 03-12 10:07:10 serving_chat.py:302] {{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}
2024-03-12T10:07:10+0900 [ERROR] [entry_service:VLLM_OpenAI:1] Application startup failed. Exiting.

The Python dependencies for further debugging are as follows:

python 3.8.10
bentoml==1.2.6
pydantic==2.6.3
pydantic_core==2.16.3
pydantic-settings==2.2.1
fastapi==0.110.0

I would appreciate any advice or solutions to resolve this issue. Thank you in advance for your assistance.

**Comment by larme** [comment]
Hi @Juhong-Namgung, thanks for reporting this bug. Seems to be python 3.8 related. I just pushed a fix, could you try it again? Thanks!

**Comment by Juhong-Namgung** [comment]
Hello,

I've applied the updated fix and can confirm that everything is working perfectly now. I really appreciate the quick turnaround on resolving this issue. Your prompt response has been incredibly helpful for the project. With the issue now resolved, I'll go ahead and close this ticket. I look forward to your continued support should any more issues arise.

Thank you!
