### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Chasapas** [bentoml/BentoVLLM#42]
Hello 
when i run bentoml serve  inside mistral-7b-instruct i get OOM but i have more than 70GB gpu free.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 826.00 MiB. GPU 
Any idea?

**Comment by EddyJens** [comment]
Same here, models of size 15GB are using ~73GB in A100 (e.g. Llama3.1, Llama3)

**Comment by larme** [comment]
Hi all, bentovllm is optimized for multiple concurrent requests, so the underlying engine will try to allocate as much GPU memory as possible to make KV cache. To reduce memory usage, add and customize the parameter `gpu_memory_utilization` [here](https://github.com/bentoml/BentoVLLM/blob/main/mixtral-8x7b-instruct/service.py#L41) like this:

```python
    ENGINE_ARGS = AsyncEngineArgs(
            model=MODEL_ID,
            max_model_len=MAX_TOKENS,
            quantization="gptq",
            dtype="half",
            enable_prefix_caching=False,
            gpu_memory_utilization=0.7,  # the default is 0.9
        )
```

But keep in mind that reducing cache size will reduce the overall token throughputs for concurrent requests.

**Comment by EddyJens** [comment]
thanks @larme, it worked like a charm!
